# Generated by Django 5.1.6 on 2025-03-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(choices=[('Beach', 'Beach'), ('Court', 'Court'), ('Snow', 'Snow')], null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Mixed', 'Mixed')], null=True)),
                ('playersOnField', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('price', models.FloatField(null=True)),
                ('minimumAge', models.IntegerField(null=True)),
                ('link', models.URLField(null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location')),
            ],
        ),
    ]
