# Generated by Django 5.1.6 on 2025-03-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='locations',
            new_name='location',
        ),
    ]
