# Generated by Django 5.1.7 on 2025-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_locations_tournament_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='poster',
            field=models.URLField(null=True),
        ),
    ]
