name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
    - backend/**
    - .github/workflows/backend.yml
  pull_request:
    branches: [ "main" ]
    paths:
    - backend/**
    - .github/workflows/backend.yml
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pipenv
    - name: Install pipenv
      run: pip install pipenv
    - name: Install Dependencies
      run: pipenv install --deploy
    - name: Run Tests
      run: pipenv run test
